-- ============================================================
-- Nova Scotia beach parks — bulk (re)seed
-- Source: https://parks.novascotia.ca/parks/all/beach (all 3 pages, 57 parks)
--
-- Replaces the 19 manually-added entries with the full published list.
--
-- IMPORTANT: amenities booleans are best-effort, inferred only from each
-- park's public summary blurb (not the per-park facility icon grid, which
-- was not scraped). Treat as a rough starting point — verify and correct
-- each entry via the app's Edit button. lat/lng are left NULL; use the
-- app's "Log a station" geocode field (Nominatim-backed) to fill them in,
-- or run a follow-up geocoding pass.
--
-- Run this in Supabase Dashboard -> SQL Editor.
-- ============================================================

begin;

delete from beaches; -- cascades to beach_flags via FK

insert into beaches (name, location, notes, contributed_by, amenities) values
('Amherst Shore', 'Northumberland Strait', 'Mixed woodland setting for camping, with some of the warmest saltwater swimming north of the Carolinas.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Battery', null, 'Historic site with lime kiln and fort remains.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Bayfield Beach', '6 km north of Exit 36, Highway 104, St. Georges Bay', 'Sand and pebble beach; supervised swimming on weekends.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Bayswater Beach', '20 km south of Highway 103, Exit 7', 'White-sand beach and picnic area, with supervised swimming, change rooms and toilets.', 'Nova Scotia Provincial Parks', '{"washrooms":true,"changeRooms":true,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Black Duck Cove', null, 'Small sandy beach and a 3.5 km shoreline walking trail.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Blomidon', 'Minas Basin', '180 m high cliffs overlooking the Minas Basin and the worlds highest tides.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Blue Sea Beach', 'Northumberland Strait', 'Dune system with low bank and wide sandy beach.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Cabots Landing', 'Aspy Bay', '3 km beach walk, with the John Cabot historic cairn.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Cape Chignecto', null, '180 m sea cliffs with 29 km of pristine coastline and 60 km of wilderness trails.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Card Lake', '17 km north of Highway 103, Exit 8, near Chester', 'Small lakeside beach with canoe launch.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Caribou-Munroes Island', null, 'Mile-long sand beach with some of the warmest saltwater swimming north of the Carolinas.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Carters Beach', null, 'One of the most scenic beaches in Nova Scotia, with white sand.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Clam Harbour Beach', '10 km south of Lake Charlotte', 'Long, wide sandy beach.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Cleveland Beach', 'East of Hubbards, Highway 103, Exit 6', 'Sandy shoreline with unsupervised swimming and limited parking.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":true,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Crystal Crescent Beach', 'Halifax Harbour mouth', 'Three white-sand crescent beaches with boardwalks and a hiking trail.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Dalem Lake', 'Boularderie East, 4 km north of Highway 105', 'White sand beach with a 2.2 km hiking trail.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Dollar Lake', 'Musquodoboit Valley', 'Sandy beach at the north end, with freshwater swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Dominion Beach', null, '1.5 km sandy beach offering supervised swimming and windsurfing.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Ellenwood Lake', 'Southern Nova Scotia, Starlight Reserve', '114 ha park with sport fishing, hiking, paddling and swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Falls Lake', null, 'Picnic park located on Falls Lake, with canoe launch.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Five Islands', 'Bay of Fundy', '90 metre sea cliffs overlooking the worlds highest tides.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Fox Harbour', 'Wallace, 4 km north of Route 6', 'Sandy beach with warm water.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Graves Island', null, 'Joined to the mainland by a short causeway; ocean-side campground.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Groves Point', '5 km south of Highway 105', 'Sand and pebble beach with warm salt water.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Gulf Shore', '5 km north of Pugwash', 'Popular public beach with warm water on the Northumberland Strait.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Heather Beach', '8 km east of East Linden, Northumberland Strait', 'Supervised swimming (July-August), warm waters.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Lake George', null, 'Freshwater sandy beach with canoe/kayak launch; accessible facilities available.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Laurie', null, 'Lakeside camping, canoeing, water skiing, fishing and swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Lawrencetown Beach', null, 'Renowned for surfing; supervised swimming (July-August). Strong rip tides and currents.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Lennox Passage', 'Isle Madame, 5 km east of Routes 320/206 junction', '2 km of shoreline, a lighthouse, and 2 km of trails.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('MacCormacks Beach', 'Eastern Passage, near Fishermans Cove', 'Boardwalk with coastal views of Halifax.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Martinique Beach', '11 km south of Musquodoboit Harbour', '3.7 km crescent white-sand beach with boardwalks and supervised swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Mavillette Beach', null, '1.5 km sandy beach with marram grass dunes and supervised swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Melmerby Beach', null, '2 km sandy beach with supervised swimming; a popular destination.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Mickey Hill', null, 'Hiking trails, boardwalks, unsupervised lake beach and picnic area.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Mira River', 'Near Sydney and Fortress Louisbourg', 'Camping on the Mira River.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Northport Beach', '3 km east of Northport', 'Red sand beach with warm water and tide pools.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Oakfield', 'Grand Lake', 'Day-use park with a small beach and boat launch.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Point Michaud Beach', null, '3 km sandy beach with supervised swimming and some surfing.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Pomquet Beach', '10 km north of Highway 104', '3 km beach, the best dune succession example in the province, with supervised swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Pondville Beach', 'Isle Madame, 2 km off Highway 320', '1 km sandy beach with dunes and a lagoon.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Port Hood Station', null, 'Cobble and white sand beaches.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Port Maitland Beach', 'Via Highway 101 Exit 33, 4 km on Route 1', '1 km sand and cobble beach with supervised swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Port Shoreham Beach', 'Chedabucto Bay', 'Sand and cobble beach with accessible facilities.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Porters Lake', null, 'Camping, boating, canoeing, water skiing, fishing and swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Powells Point', '6 km northeast of Trenton, off Highway 348', 'Some of the warmest salt water in Nova Scotia, with mixed beach types.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Queensland Beach', null, 'Popular with metro residents; supervised swimming.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Rainbow Haven Beach', null, 'Family-friendly, with supervised swimming (July-August) and kite flying.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":true,"accessible":false,"petFriendly":false,"food":false}'),
('Rissers Beach', null, 'White sand beach with a boardwalk, inland marsh and camping.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Rushtons Beach', '4 km east of Brule, in Marshville', 'Northumberland Strait beach with sandbars at low tide and a salt marsh.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Sand Hills Beach', 'South Shore, 6 km south of Highway 103, Exit 29', '2.5 km white-sand beach with a dune system and bird watching.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Summerville Beach', 'South Shore', 'About 1 km long, backed by sand dunes and saltmarsh; home to the piping plover.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Taylor Head', 'Southwest of Sheet Harbour, Eastern Shore', 'Peninsula park with 6 km of ocean frontage, hiking trails, geological features and secluded beaches.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":true,"petFriendly":false,"food":false}'),
('Thomas Raddall', 'South Shore, Port Joli Harbour', 'Over 650 hectares offering hiking, camping, picnicking and beach access.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Trout Brook', null, 'Shoreline day-use location.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('Waterside Beach', null, 'Long sandy beach with warm water and a salt marsh; boardwalk access to the beach.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}'),
('West Mabou Beach', 'Cape Breton Island', 'Cape Breton Island beach.', 'Nova Scotia Provincial Parks', '{"washrooms":false,"changeRooms":false,"showers":false,"parking":false,"lifeguard":false,"accessible":false,"petFriendly":false,"food":false}');

commit;
